# Generated by Django 5.2.1 on 2025-05-28 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('date_consumed', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_consumed', 'name'],
            },
        ),
    ]
